---
# @package _global_
_target_: ezpz.configs.TrainConfig
# ----------------------------------------------------------------------------
framework: pytorch          # ML framework to use: one of 'pytorch', 'tensorflow'
backend: 'DDP'              # Backend to use for distributed training
ds_config_path: null
port: null
seed: null
use_wandb: true
gas: 1
wandb_project_name: ezpz
# precision: null
save_to: null
load_from: null
dtype: null

ngpus: null
defaults:
  - _self_
  - logdir: default.yaml    # Defines where to run experiment using info from cfg
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: rich
  # - override hydra/launcher: joblib
  # https://hydra.cc/docs/tutorials/basic/running_your_app/logging/
  # use this to set level of only chosen command line loggers to 'DEBUG'
  # verbose: [src.train, src.utils]
  # - debug: true
  # - verbose: true
# debug: true
hydra:
  # verbose: true
  job:
    chdir: true
...
